name: CI
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 12
      - name: Setup Node
        uses: ./
        with:
          version: 4.11.1
          dest: ~/test/pnpm

      - name: 'Test: which'
        run: which pnpm && which pnpx

      # Install dependencies
      - run: pnpm install

      # Run tests
      - run: pnpm test coverage